### ISSUE TITLE
Feature Sign-Up Ajax

### ISSUE THREAD

**Issue by jaesukpark77** [marketkarly-team/marketkarly-client#104]
# 🌳 작업 브랜치
- ajax_login#104

# 🗒️ Description
- **회원가입 기능**을 구현
  - user의 정보를 json-server로 보내기
- 로그인 요청이 오면 id / pw 비교
  - unique id 값도 비교
- 로그인이 성공적으로 이루어졌다면 해당 유저의 unique id 값을 local storage에 저장

# ✅ Todo 및 진행 상황
- [ ] user의 정보를 json-server로 보내기
- [ ] 로그인 요청이 오면 id / pw 비교
- [ ] 로그인이 성공적으로 이루어졌다면 해당 유저의 unique id 값을 local storage에 저장
