### ISSUE TITLE
Feature header JS

### ISSUE THREAD

**Issue by chaewon0128** [marketkarly-team/marketkarly-client#62]
# 🌳 작업 브랜치
header#62

# 🗒️ Description
- input (type:search) clear 버튼 작업
- 고객센터 하위 숨김 메뉴 동작 

# ✅ Todo 및 진행상
- [x] input (type:search) clear 버튼 커스텀 제작 
- [ ]  input (type:search) clear 버튼 동작 완료 후 숨김 
- [x] 고객센터 mouseover 시 숨김 메뉴 등장 
- [x]  고객센터 mouseleave 시 숨김 메뉴 숨기기

## ETC
기타 사항
접근성 관점에서 수정 보완 같이 진행할 예정입니다.
- aria-label 추가, 탭 영역 보완 등
