### ISSUE TITLE
Feature  main-banner JS

### ISSUE THREAD

**Issue by realldk** [marketkarly-team/marketkarly-client#64]
# 🌳 작업 브랜치
main-banner#64
# 🗒️ Description
swiperJS를 이용해서 슬라이드 만들기
![ezgif com-gif-maker](https://user-images.githubusercontent.com/119571031/216963048-aa7e6115-7863-4b13-859c-d5e0818731ba.gif)

# ✅ Todo 및 진행상황
- [x] 자동재생
- [x] 반복재생
- [x] 마우스를 영역에 올렸을 때 자동재생 정지
- [x] 현재 페이지/총 페이지 표현하기
- [x] tab키를 이용해서 다음페이지와 이전페이지 이동하기
- [ ] tab키로 focus가 되었을 때 자동재생 정지
- [ ] tab키로 슬라이드에 진입했을 때 마지막 슬라이드로 넘어가지 않게 처리하기
- [ ] tab키로 진행하다가 아무것도 안하고 자동으로 슬라이드가 넘어가면 넘어간 index에서 tab키로 넘어가기
## ETC
기타 사항
