### ISSUE TITLE
Feature cart JS

### ISSUE THREAD

**Issue by realldk** [marketkarly-team/marketkarly-client#65]
# 🌳 작업 브랜치
cart-JS#65
# 🗒️ Description
장바구니
# ✅ Todo 및 진행상황
![ezgif com-optimize](https://user-images.githubusercontent.com/119571031/217123131-620ebad3-8b6d-49ea-a91d-9b180290ff97.gif)
- [x] 체크표시 가능하도록 만들기(CSS)
- [x] 냉장 식품 상품목록 열고 닫기
- [ ] 상위 요소에 이벤트 위임으로 한 개의 핸들러로 각 카테고리 열고 닫기
- [ ] 수량 증가에 따라 금액 변경하기
- [ ] 전체 선택
- [ ] 선택 삭제, 삭제 버튼을 누르면 해당 제품 삭제하기
- [ ] 데이터를 취합해서 주문하기 누르면 서버에 제출하기

## ETC
기타 사항
