### ISSUE TITLE
Feature navigation JS

### ISSUE THREAD

**Issue by sryung1225** [marketkarly-team/marketkarly-client#68]
# 🌳 작업 브랜치
navigation#68

# 🗒️ Description
- 네비게이션 tab 동작 추가
- 네비게이션 카테고리 하위 탭 동작 추가

# ✅ Todo 및 진행상황
- [X] 카테고리 버튼에 마우스 접근 시 카테고리맵 열리게 만들기 (mouseover, mouseleave event)
- [X] 카테고리 버튼 클릭 시, 카테고리 맵 열리게 만들고 (click) tab으로 카테고리맵 접근 가능하도록 하기
- [ ] 화면 일정 높이 스크롤 시 헤더 고정 시키기

## ETC
aria 속성 추가 검토
