### ISSUE TITLE
Feature Login & Sign-Up JS

### ISSUE THREAD

**Issue by sryung1225** [marketkarly-team/marketkarly-client#70]
# 🌳 작업 브랜치

# 🗒️ Description
회원가입/로그인 JavaScript 기능 구현 및 접근성 강화

# ✅ Todo 및 진행상황
- [x] 회원가입/로그인 HTML 이해하기
- [x] (🔥요구사항) 이메일과 비밀번호의 유효성을 확인 
  - [x] 이메일 조건 : 최소 `@`, `.` 포함
  - [x] 비밀번호 조건 : 8자 이상 입력
  - [x] 이메일과 비밀번호가 모두 입력되어 있고, 조건을 만족해야 제출 버튼이 활성화 되도록 구현해주세요.
- [ ] (🔥요구사항) 회원가입을 통해 사용자(user)를 생성하고 관리합니다.
  - [ ] 랜덤 한 문자값 (10자 이상) 을 생성 후 사용자의 Unique ID 값으로 넣어주세요.
  - [ ] 해당 유저의 Unique ID를 확인 후 로그인합니다.
  - [ ] 응답받은 Unique ID는 `localStorage`에 저장해주세요
  - [ ] 다음 번에 로그인 시 Unique ID가 존재한다면 루트 경로로 리디렉션 시켜주세요
  - [ ] 어떤 경우든 Unique ID가 유효하지 않다면 사용자에게 알리고 로그인 페이지로 리디렉션 시켜주세요
  - [ ] 로그아웃은 클라이언트 단에서 `localStorage`에 저장된 Unique ID를 삭제하는 방식으로 구현합니다.
- [x] 회원가입 > 이용약관에서 전체 선택 클릭 시 전체 선택 되도록 만들기

## ETC
- @jaesukpark77 @jeong-dev 두 분은 HTML/CSS 어떤 식으로 되어있는지 파악 우선 진행해주시면 될 것 같습니다!!
- 요구사항 외 구현하면 좋을 기능? Todo에 추가 작성 편하게 부탁드립니다... 저도 고민해볼게요 흠🤔
