### ISSUE TITLE
Feature Product List Filter JS

### ISSUE THREAD

**Issue by jaesukpark77** [marketkarly-team/marketkarly-client#80]
# 🌳 작업 브랜치
- filter_JS#50

# 🗒️ Description
PRODUCT_LIST 페이지에 속한 Filter Component 기능 구현하기

# ✅ Todo 및 진행 상황
- [x] toggle 기능 구현
- [x] 체크박스 클릭 시, 선택된 수만큼 표시
- [x] 초기화 버튼 클릭 시, 기존 선택된 정보들 초기화
- [x] 모듈화 가능한 함수 모듈화 진행

# ETC
- 서버에 있는 브랜드에 따라 각각의 개수 파악하기
