### ISSUE TITLE
Feature Product Review&Inquiry component JS

### ISSUE THREAD

**Issue by jaesukpark77** [marketkarly-team/marketkarly-client#83]
# 🌳 작업 브랜치
- review_inquiry_js#83

# 🗒️ Description
PRODUCT_DETAIL 페이지에 속한 Product Review & Inquiry Component 기능 구현하기

# ✅ Todo 및 진행 상황
- [ ] 작성 버튼 클릭하면 popup component 띄우기
- [ ] 공지사항 클릭하면 공지 보이기
- [ ] 추천수 / 최근 등록순 선택에 따라 다르게 보이기
