### ISSUE TITLE
Feature Product Review&Inquriy Pop-Up Component

### ISSUE THREAD

**Issue by jaesukpark77** [marketkarly-team/marketkarly-client#84]
# 🌳 작업 브랜치
- review_inquirt_js#84

# 🗒️ Description
PRODUCT_DETAIL 페이지에 속한 Product Review & Inquiry Component 기능 구현하기

# ✅ Todo 및 진행 상황
- [ ] popup 위치 조정
- [ ] 내용 입력하면 JSON Server로 보내기
- [ ] Server에 있는 데이터를 PRODUCT_DETAIL 페이지 Review&Inquiry component에 보여주기

# ETC
- JSON Server 구축
